### ISSUE TITLE
MVP Release Tracking Issue

### ISSUE THREAD

**Issue by MatteoJoliveau** [oxidrive/oxidrive#63]
This is the tracking issue for our first MVP release (tagged 0.1.0). Small items will be included as checklist entries. Larger tasks will be promoted to their own issue.

#### Tasks

- [ ] Update contribution guide
- [ ] Write user and admin documentation
- [ ] Add release and image signature via [cosign](https://docs.sigstore.dev/signing/quickstart/) (signing key already generated and uploaded to [GHA secrets](https://github.com/oxidrive/oxidrive/settings/secrets/actions).
